import { mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * Where file bytes live (REQ-FILE-001). The free setup uses local disk; an S3-compatible adapter
 * (Cloudflare R2 or SeaweedFS) is listed in paid-services.md for production.
 */
export abstract class FileStorage {
  abstract put(key: string, data: Buffer): Promise<void>;
  abstract get(key: string): Promise<Buffer>;
  abstract move(from: string, to: string): Promise<void>;
  abstract remove(key: string): Promise<void>;
}

/** Keys are generated by the server (UUIDs), never taken from the client. */
export class LocalDiskStorage extends FileStorage {
  constructor(private readonly root: string) {
    super();
  }

  private pathOf(key: string): string {
    if (!/^[a-z]+\/[0-9a-f-]{36}\/[0-9a-f-]{36}$/.test(key)) throw new Error('invalid storage key');
    return path.resolve(this.root, key);
  }

  async put(key: string, data: Buffer): Promise<void> {
    const file = this.pathOf(key);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, data);
  }

  get(key: string): Promise<Buffer> {
    return readFile(this.pathOf(key));
  }

  async move(from: string, to: string): Promise<void> {
    const target = this.pathOf(to);
    await mkdir(path.dirname(target), { recursive: true });
    await rename(this.pathOf(from), target);
  }

  async remove(key: string): Promise<void> {
    await rm(this.pathOf(key), { force: true });
  }
}
