"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { BarChart3, Bell, BookOpen, CalendarDays, CheckCircle2, ClipboardCheck, CreditCard, GraduationCap, LayoutDashboard, Menu, Search, Settings, ShieldCheck, Users, X } from "lucide-react";
import { AuthenticatedUser, getDashboardSummary } from "@/lib/api";

type Section = "overview" | "students" | "teachers" | "classes" | "courses" | "homework" | "exams" | "attendance" | "grades" | "payments" | "reports";
const navigation: Array<[Section, string, typeof LayoutDashboard]> = [
  ["overview", "Overview", LayoutDashboard], ["students", "Students", GraduationCap], ["teachers", "Teachers", Users],
  ["classes", "Classes & schedule", CalendarDays], ["courses", "Courses & lessons", BookOpen], ["homework", "Homework", ClipboardCheck],
  ["exams", "Exams", ShieldCheck], ["attendance", "Attendance", CheckCircle2], ["grades", "Grades", BarChart3], ["payments", "Payments", CreditCard], ["reports", "Reports", BarChart3],
];
const records: Record<string, string[][]> = {
  students: [["ST-1001", "Maya Al-Harbi", "Grade 8", "Active", "92%"], ["ST-1002", "Omar Khalid", "Grade 8", "Active", "88%"], ["ST-1003", "Lina Mansour", "Grade 7", "At risk", "64%"]],
  classes: [["Algebra Basics", "Mathematics", "Grade 8", "Teacher One", "24 / 30", "Active"], ["Reading Lab", "English", "Grade 7", "Sarah Ibrahim", "18 / 24", "Active"], ["General Science", "Science", "Grade 9", "Ahmed Nasser", "30 / 30", "Waitlist"]],
  payments: [["PM-2048", "Maya Al-Harbi", "$240", "Bank transfer", "Pending"], ["PM-2047", "Omar Khalid", "$180", "Card", "Approved"], ["PM-2046", "Lina Mansour", "$240", "Bank transfer", "Needs review"]],
};
const labels = { totalStudents: "Total students", activeStudents: "Active students", totalTeachers: "Teachers", totalClasses: "Classes", pendingPayments: "Pending payments", upcomingExams: "Upcoming exams" };
const titles: Record<Exclude<Section, "overview">, string> = { students: "Students", teachers: "Teachers", classes: "Classes & schedule", courses: "Courses & lessons", homework: "Homework", exams: "Exams", attendance: "Attendance", grades: "Grades", payments: "Payments", reports: "Reports" };
const roleSections: Record<string, Section[]> = {
  SuperAdmin: ["overview", "students", "teachers", "classes", "courses", "homework", "exams", "attendance", "grades", "payments", "reports"],
  Teacher: ["overview", "classes", "courses", "homework", "exams", "attendance", "grades", "reports"],
  Student: ["overview", "courses", "homework", "exams", "attendance", "grades"],
  Parent: ["overview", "attendance", "grades", "reports"],
};

export default function DashboardPage() {
  const router = useRouter();
  const [user, setUser] = useState<AuthenticatedUser | null>(null);
  const [summary, setSummary] = useState<Record<string, number> | null>(null);
  const [section, setSection] = useState<Section>("overview");
  const [query, setQuery] = useState("");
  const [mobileOpen, setMobileOpen] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    const token = localStorage.getItem("eduflow.token");
    const storedUser = localStorage.getItem("eduflow.user");
    if (!token || !storedUser) { router.replace("/login"); return; }
    const parsedUser = JSON.parse(storedUser) as AuthenticatedUser;
    setUser(parsedUser);
    if (parsedUser.role === "SuperAdmin" || parsedUser.role === "Teacher") {
      getDashboardSummary(token).then(setSummary).catch(() => setError("Unable to load live dashboard data."));
    }
  }, [router]);

  const select = (next: Section) => { setSection(next); setQuery(""); setMobileOpen(false); };
  const signOut = () => { localStorage.clear(); router.replace("/login"); };
  if (!user) return <main className="flex min-h-screen items-center justify-center bg-[#f6f8fb] text-slate-500">Loading workspace...</main>;
  if (user.role === "Student") return <StudentPortal user={user} signOut={signOut} />;
  const current = navigation.find((item) => item[0] === section) ?? navigation[0];

  return <main className="min-h-screen bg-[#f6f8fb] text-slate-900">
    <aside className={`fixed inset-y-0 left-0 z-30 flex w-72 flex-col border-r border-slate-200 bg-white transition-transform lg:translate-x-0 ${mobileOpen ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex h-20 items-center justify-between border-b border-slate-100 px-6"><button onClick={() => select("overview")} className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#171c38] text-lg font-black text-white">E</span><span><strong className="block text-sm tracking-[0.18em] text-[#171c38] uppercase">EduFlow</strong><small className="text-xs text-slate-400">Education OS</small></span></button><button onClick={() => setMobileOpen(false)} className="lg:hidden" aria-label="Close navigation"><X size={18} /></button></div>
      <div className="border-b border-slate-100 p-5"><div className="flex items-center gap-3 rounded-xl bg-[#f6f8fb] p-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#e8e7ff] font-bold text-[#5551b7]">{user.name[0]}</span><span><strong className="block text-sm">{user.name}</strong><small className="text-xs text-slate-400">{user.role}</small></span></div></div>
      <nav className="flex-1 overflow-y-auto px-4 py-5"><p className="mb-3 px-3 text-[10px] font-bold tracking-[0.18em] text-slate-400 uppercase">Workspace</p>{navigation.filter(([key]) => (roleSections[user.role] ?? roleSections.Student).includes(key)).map(([key, label, Icon]) => <button key={key} onClick={() => select(key)} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-medium ${section === key ? "bg-[#171c38] text-white" : "text-slate-500 hover:bg-slate-50"}`}><Icon size={17} />{label}</button>)}<p className="mb-3 mt-8 px-3 text-[10px] font-bold tracking-[0.18em] text-slate-400 uppercase">System</p><button className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm text-slate-500 hover:bg-slate-50"><Settings size={17} />Settings</button></nav>
      <div className="border-t border-slate-100 p-5"><div className="rounded-xl bg-[#f1f0ff] p-4"><p className="text-xs font-semibold text-[#5551b7]">Need help?</p><p className="mt-1 text-xs text-slate-500">Review workspace setup and permissions.</p></div></div>
    </aside>
    {mobileOpen && <button className="fixed inset-0 z-20 bg-slate-900/30 lg:hidden" aria-label="Close navigation overlay" onClick={() => setMobileOpen(false)} />}
    <div className="lg:pl-72"><header className="sticky top-0 z-10 flex h-20 items-center justify-between border-b border-slate-200 bg-white/95 px-5 lg:px-10"><div className="flex items-center gap-4"><button onClick={() => setMobileOpen(true)} className="lg:hidden" aria-label="Open navigation"><Menu size={20} /></button><div><p className="text-xs font-semibold tracking-[0.16em] text-slate-400 uppercase">Workspace / {current[1]}</p><h1 className="mt-1 text-lg font-bold">{section === "overview" ? `Good morning, ${user.name.split(" ")[0]}` : current[1]}</h1></div></div><div className="flex items-center gap-4"><button className="relative text-slate-500" aria-label="Notifications"><Bell size={19} /><span className="absolute -right-1 -top-1 h-1.5 w-1.5 rounded-full bg-rose-500" /></button><button onClick={signOut} className="text-sm font-semibold text-slate-500">Sign out</button></div></header><section className="mx-auto max-w-[1440px] px-5 py-8 lg:px-10">{error && <p className="mb-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}{section === "overview" ? <Overview summary={summary} select={select} /> : <Module section={section} query={query} setQuery={setQuery} />}</section></div>
  </main>;
}

function StudentPortal({ user, signOut }: { user: AuthenticatedUser; signOut: () => void }) {
  const [activeTab, setActiveTab] = useState("Home");
  const [isPlaying, setIsPlaying] = useState(false);
  const [showAllCourses, setShowAllCourses] = useState(false);
  const courses = [
    { title: "Mathematics Foundations", subtitle: "Algebra and problem solving", progress: 68, color: "from-[#7069e8] to-[#9e80ff]", icon: "∑" },
    { title: "General Science", subtitle: "Matter, energy, and motion", progress: 42, color: "from-[#ff8f70] to-[#ffb36e]", icon: "✦" },
    { title: "English Communication", subtitle: "Read, write, express", progress: 24, color: "from-[#42b8a5] to-[#71d4b2]", icon: "Aa" },
  ];
  const visibleCourses = showAllCourses ? courses : courses.slice(0, 2);

  return <main className="min-h-screen overflow-hidden bg-[#f7f7fb] text-[#20203a]">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10"><button className="flex items-center gap-3" onClick={() => setActiveTab("Home")}><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#20203a] text-lg font-black text-white">E</span><span className="text-sm font-black tracking-[0.2em] uppercase">EduFlow</span></button><nav className="hidden items-center gap-8 text-sm font-semibold text-[#77778e] md:flex">{["Home", "My learning", "Calendar"].map((tab) => <button key={tab} onClick={() => setActiveTab(tab)} className={activeTab === tab ? "text-[#20203a]" : "hover:text-[#20203a]"}>{tab}</button>)}</nav><div className="flex items-center gap-3"><button className="relative rounded-full bg-white p-3 shadow-sm" aria-label="Notifications"><Bell size={18} /><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-[#ff806b]" /></button><button onClick={signOut} className="rounded-full border border-[#e6e5ef] bg-white px-4 py-2.5 text-sm font-bold text-[#77778e] hover:text-[#20203a]">Sign out</button></div></header>
    <section className="mx-auto max-w-7xl px-6 pb-12 pt-8 lg:px-10"><div className="grid gap-8 lg:grid-cols-[1.15fr_0.85fr] lg:items-center"><div><p className="text-sm font-bold tracking-[0.18em] text-[#7069e8] uppercase">Your learning space</p><h1 className="mt-4 max-w-2xl text-5xl font-black leading-[1.05] tracking-[-0.04em] text-[#20203a] md:text-7xl">Keep your curiosity moving, {user.name.split(" ")[0]}.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#77778e]">You&apos;re building momentum. Pick up where you left off or explore something new today.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={() => setIsPlaying(true)} className="flex items-center gap-2 rounded-full bg-[#7069e8] px-6 py-3.5 text-sm font-bold text-white shadow-lg shadow-[#7069e8]/25 hover:bg-[#5f59d5]"><span className="text-base">▶</span> Continue learning</button><button onClick={() => setActiveTab("My learning")} className="rounded-full bg-white px-6 py-3.5 text-sm font-bold text-[#20203a] shadow-sm ring-1 ring-[#e6e5ef] hover:ring-[#7069e8]">View my path</button></div></div><div className="relative"><div className="absolute -right-8 -top-8 h-40 w-40 rounded-full bg-[#ffb88f]/30 blur-3xl" /><div className="relative overflow-hidden rounded-[2rem] bg-[#20203a] p-7 text-white shadow-2xl shadow-[#20203a]/20"><div className="flex items-start justify-between"><div><p className="text-xs font-bold tracking-[0.18em] text-[#bcb9ff] uppercase">Continue here</p><h2 className="mt-3 text-2xl font-black">Introduction to Algebra</h2><p className="mt-2 text-sm text-[#aaaac3]">Mathematics Foundations · Lesson 4</p></div><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#7069e8] text-xl">∑</span></div><div className="mt-10 flex items-end justify-between"><div><p className="text-sm text-[#aaaac3]">68% complete</p><div className="mt-3 h-2 w-48 rounded-full bg-white/15"><div className="h-2 w-[68%] rounded-full bg-[#ffad75]" /></div></div><button onClick={() => setIsPlaying(!isPlaying)} className="flex h-14 w-14 items-center justify-center rounded-full bg-white text-[#20203a] shadow-lg" aria-label={isPlaying ? "Pause lesson" : "Play lesson"}>{isPlaying ? "Ⅱ" : "▶"}</button></div></div></div></div></section>
    <section className="mx-auto max-w-7xl px-6 pb-16 lg:px-10"><div className="mb-7 flex items-end justify-between"><div><p className="text-sm font-bold tracking-[0.18em] text-[#7069e8] uppercase">Your path</p><h2 className="mt-2 text-3xl font-black tracking-tight">Courses in progress</h2></div><button onClick={() => setShowAllCourses(!showAllCourses)} className="text-sm font-bold text-[#7069e8]">{showAllCourses ? "Show less" : "See all courses"} →</button></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{visibleCourses.map((course) => <article key={course.title} className="group rounded-[1.5rem] bg-white p-3 shadow-sm ring-1 ring-[#ecebf3] transition hover:-translate-y-1 hover:shadow-xl"><div className={`flex h-40 items-end justify-between rounded-[1.1rem] bg-gradient-to-br ${course.color} p-5 text-white`}><span className="text-5xl font-black opacity-80">{course.icon}</span><span className="rounded-full bg-white/25 px-3 py-1.5 text-xs font-bold backdrop-blur-sm">{course.progress}%</span></div><div className="p-3 pt-5"><h3 className="text-lg font-black">{course.title}</h3><p className="mt-1 text-sm text-[#8a899d]">{course.subtitle}</p><div className="mt-5 h-1.5 rounded-full bg-[#eeedf4]"><div className="h-1.5 rounded-full bg-[#7069e8]" style={{ width: `${course.progress}%` }} /></div></div></article>)}</div></section>
    <section className="mx-auto grid max-w-7xl gap-6 px-6 pb-20 lg:grid-cols-[1fr_0.75fr] lg:px-10"><div className="rounded-[1.5rem] bg-[#fff3e9] p-7"><div className="flex items-start justify-between"><div><p className="text-sm font-bold tracking-[0.18em] text-[#d87955] uppercase">Coming up</p><h2 className="mt-2 text-2xl font-black">Your week, at a glance.</h2></div><CalendarDays className="text-[#d87955]" /></div><div className="mt-7 space-y-3">{[["Today", "Algebra Practice", "Due by 6:00 PM"], ["Wed, Sep 30", "Midterm Review", "45 min exam"], ["Fri, Oct 02", "Science Lab Notes", "Submission"]].map(([day, title, detail]) => <div key={title} className="flex items-center gap-4 rounded-2xl bg-white/75 p-4"><span className="w-24 text-xs font-bold text-[#d87955]">{day}</span><span className="flex-1"><strong className="block text-sm">{title}</strong><small className="text-xs text-[#8a899d]">{detail}</small></span><span className="text-[#c9a18d]">→</span></div>)}</div></div><div className="rounded-[1.5rem] bg-[#e9f8f3] p-7"><p className="text-sm font-bold tracking-[0.18em] text-[#3b9b83] uppercase">This week</p><h2 className="mt-2 text-2xl font-black">Small steps count.</h2><p className="mt-4 text-sm leading-6 text-[#638c81]">You&apos;ve studied for 3 days in a row. One more session keeps your learning streak alive.</p><div className="mt-7 flex items-end gap-2">{["M", "T", "W", "T", "F", "S", "S"].map((day, index) => <div key={`${day}-${index}`} className="flex flex-1 flex-col items-center gap-2"><span className={`h-10 w-full rounded-full ${index < 3 ? "bg-[#55b99e]" : "bg-white"}`} /><small className="text-xs font-bold text-[#638c81]">{day}</small></div>)}</div></div></section>
  </main>;
}

function Overview({ summary, select }: { summary: Record<string, number> | null; select: (next: Section) => void }) {
  return <><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-slate-500">Tuesday, September 28, 2026</p><h2 className="mt-2 text-3xl font-black tracking-tight">Your school at a glance.</h2></div><button onClick={() => select("reports")} className="rounded-xl bg-[#5551b7] px-4 py-2.5 text-sm font-bold text-white">View reports</button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{Object.entries(labels).map(([key, label]) => <article key={key} className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-3 text-3xl font-black">{summary?.[key] ?? "-"}</p><p className="mt-2 text-xs font-medium text-emerald-600">↑ 8.4% this month</p></article>)}</div><div className="mt-8 grid gap-6 xl:grid-cols-[1.4fr_0.8fr]"><section className="rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-6 py-5"><p className="text-xs font-semibold tracking-[0.16em] text-[#5551b7] uppercase">Attention needed</p><h3 className="mt-1 text-xl font-bold">Today&apos;s priorities</h3></div>{[["Homework awaiting review", "8 submissions", "homework"], ["Payment requests", "4 need approval", "payments"], ["Attendance exceptions", "3 students", "attendance"]].map(([title, detail, target]) => <button key={title} onClick={() => select(target as Section)} className="flex w-full items-center gap-4 border-b border-slate-100 px-6 py-4 text-left hover:bg-slate-50"><span className="h-2.5 w-2.5 rounded-full bg-[#7773d4]" /><span className="flex-1"><strong className="block text-sm">{title}</strong><small className="text-xs text-slate-500">{detail}</small></span><span className="text-slate-300">→</span></button>)}</section><section className="rounded-2xl bg-[#171c38] p-6 text-white"><div className="flex justify-between"><div><p className="text-xs font-semibold tracking-[0.16em] text-indigo-200 uppercase">Learning pulse</p><h3 className="mt-2 text-xl font-bold">Attendance this week</h3></div><CheckCircle2 className="text-emerald-300" /></div><p className="mt-8 text-5xl font-black">{summary?.attendancePercentage ?? 92}%</p><div className="mt-5 h-2 rounded-full bg-white/15"><div className="h-2 w-[92%] rounded-full bg-emerald-300" /></div><p className="mt-4 text-sm text-slate-300">Up 3.2% compared with last week.</p></section></div></>;
}

function Module({ section, query, setQuery }: { section: Exclude<Section, "overview">; query: string; setQuery: (value: string) => void }) {
  const data = records[section];
  const title = titles[section];
  const filtered = data?.filter((row) => row.join(" ").toLowerCase().includes(query.toLowerCase())) ?? [];
  return <><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-slate-500">Workspace module</p><h2 className="mt-2 text-3xl font-black tracking-tight">{title}</h2><p className="mt-2 text-sm text-slate-500">Manage {title.toLowerCase()} and keep your learning operation moving.</p></div><button className="rounded-xl bg-[#5551b7] px-4 py-2.5 text-sm font-bold text-white">+ Add {section === "students" ? "student" : section === "classes" ? "class" : "item"}</button></div>{data ? <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex flex-wrap justify-between gap-3 border-b border-slate-100 px-5 py-4"><div className="relative w-full max-w-sm"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${title.toLowerCase()}...`} className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-[#7773d4]" /></div><button className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-600">Filter</button></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs font-bold text-slate-500 uppercase"><tr>{(section === "students" ? ["Code", "Student", "Level", "Status", "Progress"] : section === "classes" ? ["Class", "Subject", "Level", "Teacher", "Capacity", "Status"] : ["Reference", "Student", "Amount", "Method", "Status"]).map((head) => <th key={head} className="px-5 py-4">{head}</th>)}<th /></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((row) => <tr key={row[0]} className="hover:bg-slate-50">{row.map((cell, index) => <td key={`${row[0]}-${index}`} className={`px-5 py-4 ${index === 0 ? "font-semibold text-slate-800" : "text-slate-500"}`}>{index === row.length - 1 ? <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${cell === "Active" || cell === "Approved" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{cell}</span> : cell}</td>)}<td className="px-5 py-4 text-right text-slate-400">•••</td></tr>)}</tbody></table></div></section> : <div className="flex min-h-[430px] flex-col items-center justify-center rounded-2xl border border-dashed border-slate-300 bg-white text-center"><BookOpen className="text-[#5551b7]" size={34} /><h3 className="mt-5 text-xl font-bold">{title} workspace is ready</h3><p className="mt-2 max-w-md text-sm text-slate-500">This module is wired into the application shell. Connect its API workflow to manage real records.</p></div>}</>;
}
